import { test, expect } from '@playwright/test';
import { resolve } from 'node:path';
import { defaultAcademic, emptyState, STORAGE_KEY } from '../src/state';

test('가상 시연 PDF를 직접 업로드하면 취득학점·등록학기가 자동 입력되고 동참형 확인은 생략된다', async ({ page }) => {
  await page.goto('/');
  await page.getByPlaceholder('예: 202312345').fill('202599999');
  await page.getByRole('button', { name: '교육과정 찾기' }).click();
  await page.getByRole('button', { name: '나의 졸업 계획 시작' }).click();
  await expect(page.getByRole('dialog', { name: '성적표 PDF 가져오기' })).toBeVisible();
  await page.getByLabel('성적표 PDF', { exact: true }).setInputFiles(resolve('docs/demo/가상성적표_2025학번.pdf'));
  await expect(page.locator('.import-summary')).toContainText('추출 27과목');
  await expect(page.getByLabel('가져올 현재 등록학기 수', { exact: true })).toHaveValue('4');
  await expect(page.getByRole('checkbox', { name: '4번 분류와 인정 상태 확인' })).toHaveCount(0);
  await page.getByRole('button', { name: '확인한 성적 반영', exact: true }).click();
  await expect(page.getByRole('heading', { name: '목표 평균평점을 입력해 주세요' })).toBeVisible();
  await page.getByLabel('목표 최종 평균평점', { exact: true }).fill('3.5');
  await page.getByRole('button', { name: '필요한 평균평점 계산하기' }).click();
  await expect(page.getByRole('heading', { name: '졸업까지, 한눈에.' })).toBeVisible();
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('hakjeo-mujeomu:v1')!));
  expect(saved.academic.baselineEarnedCredits).toBe(58);
  expect(saved.academic.registeredSemesters).toBe(4);
  expect(saved.semesters.map((s: { courses: { credits: number }[] }) => s.courses.reduce((sum, c) => sum + c.credits, 0))).toEqual([18, 18, 18, 18, 2]);
  expect(saved.semesters.map((s: { label: string }) => s.label)).toEqual(['2026-2', '2027-1', '2027-2', '2028-1', '2028-2']);
  const points: Record<string, number> = { 'A+': 4.5, A: 4, 'B+': 3.5, B: 3, 'C+': 2.5, C: 2, 'D+': 1.5, D: 1, F: 0 };
  const graded = saved.courses.filter((c: { grade: string }) => c.grade in points);
  const weight = graded.reduce((sum: number, c: { credits: number }) => sum + c.credits, 0);
  const earnedPoints = graded.reduce((sum: number, c: { grade: string; credits: number }) => sum + points[c.grade] * c.credits, 0);
  const required = (3.5 * (weight + 74) - earnedPoints) / 74;
  const summary = page.getByRole('region', { name: '실시간 졸업 요약', exact: true });
  await expect(summary).toContainText('74학점');
  await expect(summary).toContainText((Math.ceil(required * 1000) / 1000).toFixed(3));
  await expect(page.locator('.action-metric').nth(2)).toContainText((Math.ceil(required * 1000) / 1000).toFixed(3));
  const range = page.getByRole('region', { name: '이 계획의 평균평점 범위', exact: true });
  await expect(range).toBeVisible();
  await expect(range.getByText('최저 예상', { exact: true })).toBeVisible();
  await expect(range.getByText('최고 예상', { exact: true })).toBeVisible();
  await expect(range.getByRole('img')).toHaveAttribute('aria-label', `예상 누적 평균평점 범위 ${(earnedPoints / (weight + 74)).toFixed(2)}부터 ${((earnedPoints + 74 * 4.5) / (weight + 74)).toFixed(2)}, 목표 3.5`);
  await page.getByRole('button', { name: '적용 규칙 · 설정', exact: true }).click();
  await expect(page.getByLabel('기준 총 취득학점', { exact: false })).toHaveValue('58');
  await expect(page.getByLabel('현재 등록학기 수', { exact: false })).toHaveValue('4');
  await page.getByRole('button', { name: '나의 대시보드', exact: true }).click();
  await expect(page.getByRole('main').getByText('졸업까지 남은 총학점', { exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: '어떤 구분을 몇 학점 더 들어야 하나요?' })).toBeVisible();
  await page.getByLabel('목표 최종 평균평점', { exact: true }).fill('3.6');
  await page.getByRole('button', { name: '적용', exact: true }).click();
  await expect(page.getByRole('alert')).toHaveCount(0);
  await page.getByRole('button', { name: '학기별 계획', exact: true }).click();
  await expect(page.locator('.plan-overview')).toContainText('5개 학기 · 74/74학점 계획');
  await expect(summary).toBeVisible();
  await page.getByRole('button', { name: '2026-2 가상 과목 1 계획 수정', exact: true }).click();
  await page.getByRole('dialog').getByRole('spinbutton', { name: '과목 학점 수', exact: true }).fill('2');
  await page.getByRole('dialog').getByRole('combobox', { name: '성적 방식', exact: true }).selectOption('pass');
  await page.getByRole('dialog').getByRole('combobox', { name: '과목 구분', exact: true }).selectOption('primary-elective');
  await page.getByRole('button', { name: '수정 사항 반영' }).click();
  await expect(page.locator('.plan-overview')).toContainText('평점 반영 71');
  await expect(page.locator('.plan-overview')).toContainText('5개 학기 · 73/74학점 계획');
  const editedRequired = (3.6 * (weight + 71) - earnedPoints) / 71;
  await expect(summary).toContainText((Math.ceil(editedRequired * 1000) / 1000).toFixed(3));
  await page.getByRole('button', { name: '나의 대시보드', exact: true }).click();
  await page.getByLabel('목표 최종 평균평점', { exact: true }).fill('3.5');
  await page.getByRole('button', { name: '적용', exact: true }).click();
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('hakjeo-mujeomu:v1')!).semesters[0].courses[0].graded)).toBe(false);
  await expect(range.getByRole('img')).toHaveAttribute('aria-label', `예상 누적 평균평점 범위 ${(earnedPoints / (weight + 71)).toFixed(2)}부터 ${((earnedPoints + 71 * 4.5) / (weight + 71)).toFixed(2)}, 목표 3.5`);
  await page.getByLabel('목표 최종 평균평점', { exact: true }).fill('4.5');
  await page.getByRole('button', { name: '적용', exact: true }).click();
  const impossibleBadge = page.locator('.action-metric > .badge');
  await expect(impossibleBadge).toHaveText('현재 계획으로 목표 달성 불가');
  for (const width of [1280, 1201, 390]) {
    await page.setViewportSize({ width, height: 844 });
    await expect(impossibleBadge).toHaveCSS('font-size', '10px');
    await expect(impossibleBadge).toHaveCSS('white-space', 'nowrap');
    expect(await impossibleBadge.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true);
  }
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
});

test('삭제 전후 비교는 현재 평점과 남은 졸업학점 두 행만 표시하고 선택에 따라 갱신된다', async ({ page }) => {
  const state = emptyState({ ...defaultAcademic(2025), registeredSemesters: 4, enrollmentStatus: 'enrolled', baselineEarnedCredits: 96 });
  state.targetGpa = 3.5;
  state.courses = [
    ...Array.from({ length: 30 }, (_, i) => ({ id: `a-${i}`, name: `검증 A 과목 ${i + 1}`, semester: '2025-2', categoryId: 'primary-elective', credits: 3, grade: 'A', deletionEligibility: 'eligible' as const })),
    ...[{ id: 'low', name: '검증 C+ 과목', grade: 'C+' }, { id: 'failed', name: '검증 F 과목', grade: 'F' }, { id: 'pass', name: '검증 P 과목', grade: 'P' }].map(c => ({ ...c, semester: '2025-2', categoryId: 'primary-elective', credits: 3, deletionEligibility: 'eligible' as const })),
  ];
  await page.addInitScript(({ key, saved }) => localStorage.setItem(key, JSON.stringify(saved)), { key: STORAGE_KEY, saved: state });
  await page.goto('/');
  const comparison = page.getByRole('region', { name: '삭제 전후 비교', exact: true });
  await expect(comparison).toBeVisible();
  await expect(comparison.locator('tbody tr')).toHaveCount(2);
  const gpa = comparison.getByRole('row', { name: /현재 평균평점/ });
  const credits = comparison.getByRole('row', { name: /졸업까지 남은 이수 학점/ });
  await expect(gpa.getByRole('cell')).toHaveText(['3.83', '3.83']);
  await expect(credits.getByRole('cell')).toHaveText(['36학점', '36학점']);
  await comparison.getByRole('button', { name: '삭제 과목 선택' }).click();
  await page.getByRole('checkbox', { name: '검증 C+ 과목 삭제 대상으로 선택', exact: true }).check();
  await page.getByRole('button', { name: '나의 대시보드', exact: true }).click();
  await expect(gpa.getByRole('cell')).toHaveText(['3.83', '3.87']);
  await expect(credits.getByRole('cell')).toHaveText(['36학점', '39학점']);
  await expect(page.getByRole('region', { name: '실시간 졸업 요약' })).toContainText('39학점');
  await comparison.getByRole('button', { name: '삭제 과목 선택' }).click();
  await page.getByRole('checkbox', { name: '검증 F 과목 삭제 대상으로 선택', exact: true }).check();
  await page.getByRole('button', { name: '나의 대시보드', exact: true }).click();
  await expect(gpa.getByRole('cell')).toHaveText(['3.83', '4.00']);
  await expect(credits.getByRole('cell')).toHaveText(['36학점', '39학점']);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: '메뉴 열기' }).click();
  await expect(page.getByRole('region', { name: '실시간 졸업 요약' })).toBeVisible();
  await expect(comparison).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
});
